const SUPABASE_URL = "https://zsclbpigriyjsarwwyod.supabase.co";
const SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzY2xicGlncml5anNhcnd3eW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkxMjgwODAsImV4cCI6MjEwNDcwNDA4MH0.LXgM3w7AlIU3Fo2dACMMLGXwoIBl6LTWl_qjTSk-2KQ";
